# Generated by Django 3.1.4 on 2020-12-06 22:16

from django.db import migrations, models
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledetailpage',
            name='custom_title',
        ),
        migrations.AddField(
            model_name='articledetailpage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articledetailpage',
            name='title_subtext',
            field=wagtail.core.fields.RichTextField(max_length=200, null=True),
        ),
    ]
