# Generated by Django 3.1.5 on 2021-01-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetailpage',
            name='image_credits_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
