# Generated by Django 3.1.4 on 2020-12-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articlecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['name'], 'verbose_name': 'Article Topic', 'verbose_name_plural': 'Article Topics'},
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='A slug to identify articles by this topic.', max_length=150, verbose_name='slug'),
        ),
    ]
