# Generated by Django 3.1.4 on 2020-12-07 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20201207_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledetailpage',
            name='topics',
        ),
        migrations.AddField(
            model_name='articledetailpage',
            name='topics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.articletopic'),
        ),
    ]
