# Generated by Django 3.1.4 on 2020-12-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20201207_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articledetailpage',
            old_name='topics',
            new_name='topic',
        ),
    ]
