# Generated by Django 3.1.4 on 2020-12-08 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_articledetailpagestrange'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoArticlePage',
            fields=[
                ('articledetailpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.articledetailpage')),
                ('youtube_video_id', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('articles.articledetailpage',),
        ),
    ]
