# Generated by Django 3.1.4 on 2020-12-09 02:10

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_videoarticlepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletopic',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, help_text='A slug to identify articles by this topic.', max_length=100, populate_from='name', verbose_name='slug'),
        ),
    ]
