# Generated by Django 3.1.4 on 2020-12-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20201208_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetailpage',
            name='image_credits',
            field=models.CharField(help_text="Acknowledge the image's producer", max_length=100, null=True),
        ),
    ]
