# Generated by Django 3.1.4 on 2021-01-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20201230_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetailpage',
            name='image_credits',
            field=models.CharField(blank=True, help_text="Acknowledge the image's producer", max_length=100, null=True),
        ),
    ]
