# Generated by Django 3.1.4 on 2021-01-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20210107_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelistingpage',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Overwrites the default title', max_length=100, null=True),
        ),
    ]
