# Generated by Django 3.1.5 on 2021-01-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20210118_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletopic',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
