# Generated by Django 3.1.5 on 2021-01-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigations', '0003_auto_20210119_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
