# Generated by Django 3.1.4 on 2020-12-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201202_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StarsightSettings',
        ),
    ]
