# Generated by Django 3.1.4 on 2020-12-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201204_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='default_apod_image_text',
            field=models.CharField(max_length=276, null=True),
        ),
    ]
