# Generated by Django 3.1.4 on 2020-12-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_default_apod_image_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='default_apod_image_credits',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='default_apod_image_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
