# Generated by Django 3.1.4 on 2020-12-04 18:03

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201204_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='default_apod_image_text',
            field=wagtail.core.fields.RichTextField(max_length=276, null=True),
        ),
    ]
