# Generated by Django 3.1.4 on 2020-12-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepagecarouselimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StarsightSettings',
        ),
    ]
