# Generated by Django 3.1.4 on 2020-12-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='starsightsettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook URL', null=True),
        ),
        migrations.AddField(
            model_name='starsightsettings',
            name='twitter',
            field=models.URLField(blank=True, help_text='Twitter URL', null=True),
        ),
        migrations.AddField(
            model_name='starsightsettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='YouTube Channel URL', null=True),
        ),
    ]
