# Generated by Django 3.1.4 on 2020-12-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_remove_starsightsettings_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='starsightsettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram URL', null=True),
        ),
    ]
